
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/bodas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  files: files/